"""add samba tables

Revision ID: 01cc90e9f8af
Revises: 
Create Date: 2026-03-16 10:32:37.720359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '01cc90e9f8af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samba_category_mapping',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('source_site', sa.Text(), nullable=False),
    sa.Column('source_category', sa.Text(), nullable=False),
    sa.Column('target_mappings', sa.JSON(), nullable=True),
    sa.Column('applied_policy_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samba_category_mapping_source_site'), 'samba_category_mapping', ['source_site'], unique=False)
    op.create_table('samba_category_tree',
    sa.Column('site_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cat1', sa.JSON(), nullable=True),
    sa.Column('cat2', sa.JSON(), nullable=True),
    sa.Column('cat3', sa.JSON(), nullable=True),
    sa.Column('cat4', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('site_name')
    )
    op.create_table('samba_channel',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('fee_rate', sa.Float(), nullable=False),
    sa.Column('products', sa.JSON(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('api_secret', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samba_channel_platform'), 'samba_channel', ['platform'], unique=False)
    op.create_table('samba_collected_product',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('source_site', sa.Text(), nullable=False),
    sa.Column('search_filter_id', sa.Text(), nullable=True),
    sa.Column('site_product_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('name_ja', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('original_price', sa.Float(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('detail_html', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('category1', sa.Text(), nullable=True),
    sa.Column('category2', sa.Text(), nullable=True),
    sa.Column('category3', sa.Text(), nullable=True),
    sa.Column('category4', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('applied_policy_id', sa.Text(), nullable=True),
    sa.Column('market_prices', sa.JSON(), nullable=True),
    sa.Column('market_enabled', sa.JSON(), nullable=True),
    sa.Column('registered_accounts', sa.JSON(), nullable=True),
    sa.Column('is_sold_out', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('price_before_change', sa.Float(), nullable=True),
    sa.Column('price_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kream_data', sa.JSON(), nullable=True),
    sa.Column('manufacturer', sa.Text(), nullable=True),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samba_collected_product_search_filter_id'), 'samba_collected_product', ['search_filter_id'], unique=False)
    op.create_index(op.f('ix_samba_collected_product_site_product_id'), 'samba_collected_product', ['site_product_id'], unique=False)
    op.create_index(op.f('ix_samba_collected_product_source_site'), 'samba_collected_product', ['source_site'], unique=False)
    op.create_index(op.f('ix_samba_collected_product_status'), 'samba_collected_product', ['status'], unique=False)
    op.create_table('samba_contact_log',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('order_id', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('recipient', sa.Text(), nullable=True),
    sa.Column('template', sa.Text(), nullable=True),
    sa.Column('custom_message', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samba_contact_log_order_id'), 'samba_contact_log', ['order_id'], unique=False)
    op.create_index(op.f('ix_samba_contact_log_status'), 'samba_contact_log', ['status'], unique=False)
    op.create_table('samba_forbidden_word',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('word', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('group_id', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samba_forbidden_word_type'), 'samba_forbidden_word', ['type'], unique=False)
    op.create_table('samba_market_account',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('market_type', sa.Text(), nullable=False),
    sa.Column('market_name', sa.Text(), nullable=False),
    sa.Column('account_label', sa.Text(), nullable=False),
    sa.Column('seller_id', sa.Text(), nullable=True),
    sa.Column('business_name', sa.Text(), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('api_secret', sa.Text(), nullable=True),
    sa.Column('additional_fields', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samba_market_account_is_active'), 'samba_market_account', ['is_active'], unique=False)
    op.create_index(op.f('ix_samba_market_account_market_type'), 'samba_market_account', ['market_type'], unique=False)
    op.create_index(op.f('ix_samba_market_account_seller_id'), 'samba_market_account', ['seller_id'], unique=False)
    op.create_table('samba_order',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('order_number', sa.Text(), nullable=False),
    sa.Column('channel_id', sa.Text(), nullable=True),
    sa.Column('channel_name', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('product_name', sa.Text(), nullable=True),
    sa.Column('source_site', sa.Text(), nullable=True),
    sa.Column('customer_name', sa.Text(), nullable=True),
    sa.Column('customer_phone', sa.Text(), nullable=True),
    sa.Column('customer_address', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('fee_rate', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('profit_rate', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('payment_status', sa.Text(), nullable=False),
    sa.Column('shipping_status', sa.Text(), nullable=False),
    sa.Column('return_status', sa.Text(), nullable=True),
    sa.Column('shipping_company', sa.Text(), nullable=True),
    sa.Column('tracking_number', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('shipment_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samba_order_channel_id'), 'samba_order', ['channel_id'], unique=False)
    op.create_index(op.f('ix_samba_order_order_number'), 'samba_order', ['order_number'], unique=False)
    op.create_index(op.f('ix_samba_order_product_id'), 'samba_order', ['product_id'], unique=False)
    op.create_index(op.f('ix_samba_order_status'), 'samba_order', ['status'], unique=False)
    op.create_table('samba_policy',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('site_name', sa.Text(), nullable=True),
    sa.Column('pricing', sa.JSON(), nullable=True),
    sa.Column('market_policies', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('samba_product',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('name_ja', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_site', sa.Text(), nullable=True),
    sa.Column('site_product_id', sa.Text(), nullable=True),
    sa.Column('source_price', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('margin_rate', sa.Float(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('category1', sa.Text(), nullable=True),
    sa.Column('category2', sa.Text(), nullable=True),
    sa.Column('category3', sa.Text(), nullable=True),
    sa.Column('category4', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('market_prices', sa.JSON(), nullable=True),
    sa.Column('market_enabled', sa.JSON(), nullable=True),
    sa.Column('registered_accounts', sa.JSON(), nullable=True),
    sa.Column('applied_policy_id', sa.Text(), nullable=True),
    sa.Column('price_before_change', sa.Float(), nullable=True),
    sa.Column('price_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_sold_out', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samba_product_brand'), 'samba_product', ['brand'], unique=False)
    op.create_index(op.f('ix_samba_product_category'), 'samba_product', ['category'], unique=False)
    op.create_index(op.f('ix_samba_product_site_product_id'), 'samba_product', ['site_product_id'], unique=False)
    op.create_index(op.f('ix_samba_product_source_site'), 'samba_product', ['source_site'], unique=False)
    op.create_index(op.f('ix_samba_product_status'), 'samba_product', ['status'], unique=False)
    op.create_table('samba_return',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('requested_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('approval_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samba_return_order_id'), 'samba_return', ['order_id'], unique=False)
    op.create_index(op.f('ix_samba_return_status'), 'samba_return', ['status'], unique=False)
    op.create_table('samba_search_filter',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('source_site', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=True),
    sa.Column('category_filter', sa.Text(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('exclude_sold_out', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samba_search_filter_source_site'), 'samba_search_filter', ['source_site'], unique=False)
    op.create_table('samba_settings',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('samba_shipment',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('product_id', sa.Text(), nullable=False),
    sa.Column('target_account_ids', sa.JSON(), nullable=True),
    sa.Column('update_items', sa.JSON(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('update_result', sa.JSON(), nullable=True),
    sa.Column('transmit_result', sa.JSON(), nullable=True),
    sa.Column('transmit_error', sa.JSON(), nullable=True),
    sa.Column('mapped_categories', sa.JSON(), nullable=True),
    sa.Column('lotte_details', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samba_shipment_product_id'), 'samba_shipment', ['product_id'], unique=False)
    op.create_index(op.f('ix_samba_shipment_status'), 'samba_shipment', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_samba_shipment_status'), table_name='samba_shipment')
    op.drop_index(op.f('ix_samba_shipment_product_id'), table_name='samba_shipment')
    op.drop_table('samba_shipment')
    op.drop_table('samba_settings')
    op.drop_index(op.f('ix_samba_search_filter_source_site'), table_name='samba_search_filter')
    op.drop_table('samba_search_filter')
    op.drop_index(op.f('ix_samba_return_status'), table_name='samba_return')
    op.drop_index(op.f('ix_samba_return_order_id'), table_name='samba_return')
    op.drop_table('samba_return')
    op.drop_index(op.f('ix_samba_product_status'), table_name='samba_product')
    op.drop_index(op.f('ix_samba_product_source_site'), table_name='samba_product')
    op.drop_index(op.f('ix_samba_product_site_product_id'), table_name='samba_product')
    op.drop_index(op.f('ix_samba_product_category'), table_name='samba_product')
    op.drop_index(op.f('ix_samba_product_brand'), table_name='samba_product')
    op.drop_table('samba_product')
    op.drop_table('samba_policy')
    op.drop_index(op.f('ix_samba_order_status'), table_name='samba_order')
    op.drop_index(op.f('ix_samba_order_product_id'), table_name='samba_order')
    op.drop_index(op.f('ix_samba_order_order_number'), table_name='samba_order')
    op.drop_index(op.f('ix_samba_order_channel_id'), table_name='samba_order')
    op.drop_table('samba_order')
    op.drop_index(op.f('ix_samba_market_account_seller_id'), table_name='samba_market_account')
    op.drop_index(op.f('ix_samba_market_account_market_type'), table_name='samba_market_account')
    op.drop_index(op.f('ix_samba_market_account_is_active'), table_name='samba_market_account')
    op.drop_table('samba_market_account')
    op.drop_index(op.f('ix_samba_forbidden_word_type'), table_name='samba_forbidden_word')
    op.drop_table('samba_forbidden_word')
    op.drop_index(op.f('ix_samba_contact_log_status'), table_name='samba_contact_log')
    op.drop_index(op.f('ix_samba_contact_log_order_id'), table_name='samba_contact_log')
    op.drop_table('samba_contact_log')
    op.drop_index(op.f('ix_samba_collected_product_status'), table_name='samba_collected_product')
    op.drop_index(op.f('ix_samba_collected_product_source_site'), table_name='samba_collected_product')
    op.drop_index(op.f('ix_samba_collected_product_site_product_id'), table_name='samba_collected_product')
    op.drop_index(op.f('ix_samba_collected_product_search_filter_id'), table_name='samba_collected_product')
    op.drop_table('samba_collected_product')
    op.drop_index(op.f('ix_samba_channel_platform'), table_name='samba_channel')
    op.drop_table('samba_channel')
    op.drop_table('samba_category_tree')
    op.drop_index(op.f('ix_samba_category_mapping_source_site'), table_name='samba_category_mapping')
    op.drop_table('samba_category_mapping')
    # ### end Alembic commands ###
