"""store_care 스케줄 + 구매이력 테이블

Revision ID: 2a3ab66db7a7
Revises: a2092d514fce
Create Date: 2026-03-25 07:26:54.544891

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2a3ab66db7a7"
down_revision: Union[str, Sequence[str], None] = "a2092d514fce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "store_care_purchases",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("schedule_id", sa.String(), nullable=True),
        sa.Column("market_type", sa.String(length=30), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("product_id", sa.String(), nullable=True),
        sa.Column("product_name", sa.Text(), nullable=True),
        sa.Column("product_no", sa.String(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.Column("order_no", sa.String(), nullable=True),
        sa.Column("buyer_account", sa.String(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_store_care_purchases_status"),
        "store_care_purchases",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_store_care_purchases_tenant_id"),
        "store_care_purchases",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "store_care_schedules",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("market_type", sa.String(length=30), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("account_label", sa.String(), nullable=True),
        sa.Column("interval_hours", sa.Integer(), nullable=True),
        sa.Column("daily_target", sa.Integer(), nullable=True),
        sa.Column("daily_done", sa.Integer(), nullable=True),
        sa.Column("product_selection", sa.String(length=20), nullable=True),
        sa.Column("product_ids", sa.JSON(), nullable=True),
        sa.Column("min_price", sa.Integer(), nullable=True),
        sa.Column("max_price", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_store_care_schedules_status"),
        "store_care_schedules",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_store_care_schedules_tenant_id"),
        "store_care_schedules",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_store_care_schedules_tenant_id"), table_name="store_care_schedules"
    )
    op.drop_index(
        op.f("ix_store_care_schedules_status"), table_name="store_care_schedules"
    )
    op.drop_table("store_care_schedules")
    op.drop_index(
        op.f("ix_store_care_purchases_tenant_id"), table_name="store_care_purchases"
    )
    op.drop_index(
        op.f("ix_store_care_purchases_status"), table_name="store_care_purchases"
    )
    op.drop_table("store_care_purchases")
    # ### end Alembic commands ###
