"""add_samba_search_cache

Revision ID: 2b3042f4d3b6
Revises: 37e835a156d6
Create Date: 2026-04-16 22:20:33.496353

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "2b3042f4d3b6"
down_revision: Union[str, Sequence[str], None] = "37e835a156d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "samba_search_cache",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
        sa.Column("tenant_id", sa.String(length=100), nullable=True),
        sa.Column("source_site", sa.String(length=50), nullable=False),
        sa.Column("keyword", sa.String(length=200), nullable=False),
        sa.Column("products", sa.JSON(), nullable=True),
        sa.Column("ttl_minutes", sa.Integer(), server_default="60", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_samba_search_cache_source_site"),
        "samba_search_cache",
        ["source_site"],
        unique=False,
    )
    op.create_index(
        op.f("ix_samba_search_cache_tenant_id"),
        "samba_search_cache",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_samba_search_cache_tenant_id"), table_name="samba_search_cache"
    )
    op.drop_index(
        op.f("ix_samba_search_cache_source_site"), table_name="samba_search_cache"
    )
    op.drop_table("samba_search_cache")
    # ### end Alembic commands ###
