"""add_ix_scp_tenant_source_name

Revision ID: 39f5332d495f
Revises: 8e5e540912c5
Create Date: 2026-04-20 09:33:45.861443

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "39f5332d495f"
down_revision: Union[str, Sequence[str], None] = "8e5e540912c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_scp_tenant_source_name",
        "samba_collected_product",
        ["tenant_id", "source_site", "name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_scp_tenant_source_name", table_name="samba_collected_product")
    # ### end Alembic commands ###
