"""add_requested_count_to_search_filter

Revision ID: 5702896235d6
Revises: 01cc90e9f8af
Create Date: 2026-03-17 08:15:41.661585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5702896235d6'
down_revision: Union[str, Sequence[str], None] = '01cc90e9f8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samba_search_filter', sa.Column('requested_count', sa.Integer(), server_default='100', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samba_search_filter', 'requested_count')
    # ### end Alembic commands ###
