"""tenant 모델 + 전체 samba 테이블 tenant_id 추가

Revision ID: 6497c73e78e8
Revises: 4895f1d6be8d
Create Date: 2026-03-24 23:11:34.502741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6497c73e78e8'
down_revision: Union[str, Sequence[str], None] = '4895f1d6be8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samba_category_mapping', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_samba_category_mapping_tenant_id'), 'samba_category_mapping', ['tenant_id'], unique=False)
    op.add_column('samba_collected_product', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_samba_collected_product_tenant_id'), 'samba_collected_product', ['tenant_id'], unique=False)
    op.add_column('samba_detail_template', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_samba_detail_template_tenant_id'), 'samba_detail_template', ['tenant_id'], unique=False)
    op.add_column('samba_forbidden_word', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_samba_forbidden_word_tenant_id'), 'samba_forbidden_word', ['tenant_id'], unique=False)
    op.add_column('samba_market_account', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_samba_market_account_tenant_id'), 'samba_market_account', ['tenant_id'], unique=False)
    op.add_column('samba_name_rule', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_samba_name_rule_tenant_id'), 'samba_name_rule', ['tenant_id'], unique=False)
    op.add_column('samba_order', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_samba_order_tenant_id'), 'samba_order', ['tenant_id'], unique=False)
    op.add_column('samba_policy', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_samba_policy_tenant_id'), 'samba_policy', ['tenant_id'], unique=False)
    op.add_column('samba_product', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_samba_product_tenant_id'), 'samba_product', ['tenant_id'], unique=False)
    op.add_column('samba_search_filter', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_samba_search_filter_tenant_id'), 'samba_search_filter', ['tenant_id'], unique=False)
    op.add_column('samba_settings', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_samba_settings_tenant_id'), 'samba_settings', ['tenant_id'], unique=False)
    op.add_column('samba_shipment', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_samba_shipment_tenant_id'), 'samba_shipment', ['tenant_id'], unique=False)
    op.add_column('samba_user', sa.Column('tenant_id', sa.String(), nullable=True))
    op.add_column('samba_user', sa.Column('role', sa.String(), nullable=True))
    op.create_index(op.f('ix_samba_user_tenant_id'), 'samba_user', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_samba_user_tenant_id'), table_name='samba_user')
    op.drop_column('samba_user', 'role')
    op.drop_column('samba_user', 'tenant_id')
    op.drop_index(op.f('ix_samba_shipment_tenant_id'), table_name='samba_shipment')
    op.drop_column('samba_shipment', 'tenant_id')
    op.drop_index(op.f('ix_samba_settings_tenant_id'), table_name='samba_settings')
    op.drop_column('samba_settings', 'tenant_id')
    op.drop_index(op.f('ix_samba_search_filter_tenant_id'), table_name='samba_search_filter')
    op.drop_column('samba_search_filter', 'tenant_id')
    op.drop_index(op.f('ix_samba_product_tenant_id'), table_name='samba_product')
    op.drop_column('samba_product', 'tenant_id')
    op.drop_index(op.f('ix_samba_policy_tenant_id'), table_name='samba_policy')
    op.drop_column('samba_policy', 'tenant_id')
    op.drop_index(op.f('ix_samba_order_tenant_id'), table_name='samba_order')
    op.drop_column('samba_order', 'tenant_id')
    op.drop_index(op.f('ix_samba_name_rule_tenant_id'), table_name='samba_name_rule')
    op.drop_column('samba_name_rule', 'tenant_id')
    op.drop_index(op.f('ix_samba_market_account_tenant_id'), table_name='samba_market_account')
    op.drop_column('samba_market_account', 'tenant_id')
    op.drop_index(op.f('ix_samba_forbidden_word_tenant_id'), table_name='samba_forbidden_word')
    op.drop_column('samba_forbidden_word', 'tenant_id')
    op.drop_index(op.f('ix_samba_detail_template_tenant_id'), table_name='samba_detail_template')
    op.drop_column('samba_detail_template', 'tenant_id')
    op.drop_index(op.f('ix_samba_collected_product_tenant_id'), table_name='samba_collected_product')
    op.drop_column('samba_collected_product', 'tenant_id')
    op.drop_index(op.f('ix_samba_category_mapping_tenant_id'), table_name='samba_category_mapping')
    op.drop_column('samba_category_mapping', 'tenant_id')
    # ### end Alembic commands ###
