"""add_group_product_fields

Revision ID: 7b57da114385
Revises: 1fd6c0f682e9
Create Date: 2026-03-22 09:14:27.256376

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b57da114385"
down_revision: Union[str, Sequence[str], None] = "1fd6c0f682e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "samba_collected_product",
        sa.Column("group_key", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "samba_collected_product",
        sa.Column("similar_no", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "samba_collected_product",
        sa.Column("group_product_no", sa.BigInteger(), nullable=True),
    )
    op.create_index(
        op.f("ix_samba_collected_product_group_key"),
        "samba_collected_product",
        ["group_key"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_samba_collected_product_group_key"),
        table_name="samba_collected_product",
    )
    op.drop_column("samba_collected_product", "group_product_no")
    op.drop_column("samba_collected_product", "similar_no")
    op.drop_column("samba_collected_product", "group_key")
    # ### end Alembic commands ###
