"""cs_inquiry 모델 env.py 추가 - 인덱스 및 id 타입 보정

Revision ID: 873871a20399
Revises: 2b3042f4d3b6
Create Date: 2026-04-17 00:01:54.664941

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "873871a20399"
down_revision: Union[str, Sequence[str], None] = "2b3042f4d3b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "samba_cs_inquiry",
        "id",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(length=30),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_samba_cs_inquiry_account_id"),
        "samba_cs_inquiry",
        ["account_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_samba_cs_inquiry_collected_product_id"),
        "samba_cs_inquiry",
        ["collected_product_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_samba_cs_inquiry_external_id"),
        "samba_cs_inquiry",
        ["external_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_samba_cs_inquiry_inquiry_type"),
        "samba_cs_inquiry",
        ["inquiry_type"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_samba_cs_inquiry_market"),
        "samba_cs_inquiry",
        ["market"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_samba_cs_inquiry_market_inquiry_no"),
        "samba_cs_inquiry",
        ["market_inquiry_no"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_samba_cs_inquiry_market_order_id"),
        "samba_cs_inquiry",
        ["market_order_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_samba_cs_inquiry_market_product_no"),
        "samba_cs_inquiry",
        ["market_product_no"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_samba_cs_inquiry_reply_status"),
        "samba_cs_inquiry",
        ["reply_status"],
        unique=False,
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_samba_cs_inquiry_reply_status"), table_name="samba_cs_inquiry"
    )
    op.drop_index(
        op.f("ix_samba_cs_inquiry_market_product_no"), table_name="samba_cs_inquiry"
    )
    op.drop_index(
        op.f("ix_samba_cs_inquiry_market_order_id"), table_name="samba_cs_inquiry"
    )
    op.drop_index(
        op.f("ix_samba_cs_inquiry_market_inquiry_no"), table_name="samba_cs_inquiry"
    )
    op.drop_index(op.f("ix_samba_cs_inquiry_market"), table_name="samba_cs_inquiry")
    op.drop_index(
        op.f("ix_samba_cs_inquiry_inquiry_type"), table_name="samba_cs_inquiry"
    )
    op.drop_index(
        op.f("ix_samba_cs_inquiry_external_id"), table_name="samba_cs_inquiry"
    )
    op.drop_index(
        op.f("ix_samba_cs_inquiry_collected_product_id"), table_name="samba_cs_inquiry"
    )
    op.drop_index(op.f("ix_samba_cs_inquiry_account_id"), table_name="samba_cs_inquiry")
    op.alter_column(
        "samba_cs_inquiry",
        "id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=30),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
