"""add_samba_message_log

Revision ID: 8e5e540912c5
Revises: 540a56de92dd
Create Date: 2026-04-20 08:44:48.701546

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "8e5e540912c5"
down_revision: Union[str, Sequence[str], None] = "540a56de92dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "samba_message_log",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("order_id", sa.Text(), nullable=True),
        sa.Column("customer_phone", sa.Text(), nullable=True),
        sa.Column("message_type", sa.Text(), nullable=False),
        sa.Column("template_raw", sa.Text(), nullable=True),
        sa.Column("rendered_message", sa.Text(), nullable=False),
        sa.Column("receiver", sa.Text(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("success", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("result_message", sa.Text(), nullable=True),
        sa.Column("msg_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_samba_message_log_customer_phone"),
        "samba_message_log",
        ["customer_phone"],
        unique=False,
    )
    op.create_index(
        op.f("ix_samba_message_log_message_type"),
        "samba_message_log",
        ["message_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_samba_message_log_order_id"),
        "samba_message_log",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_samba_message_log_tenant_id"),
        "samba_message_log",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_samba_message_log_tenant_id"), table_name="samba_message_log"
    )
    op.drop_index(op.f("ix_samba_message_log_order_id"), table_name="samba_message_log")
    op.drop_index(
        op.f("ix_samba_message_log_message_type"), table_name="samba_message_log"
    )
    op.drop_index(
        op.f("ix_samba_message_log_customer_phone"), table_name="samba_message_log"
    )
    op.drop_table("samba_message_log")
    # ### end Alembic commands ###
