"""add_samba_cs_inquiry_table

Revision ID: a2092d514fce
Revises: d53a0e1e5c2c
Create Date: 2026-03-25 07:13:27.821134

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a2092d514fce"
down_revision: Union[str, Sequence[str], None] = "d53a0e1e5c2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "samba_cs_inquiry",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
        sa.Column("market", sa.Text(), nullable=False),
        sa.Column("market_order_id", sa.Text(), nullable=True),
        sa.Column("account_name", sa.Text(), nullable=True),
        sa.Column("inquiry_type", sa.Text(), nullable=False),
        sa.Column("questioner", sa.Text(), nullable=True),
        sa.Column("product_name", sa.Text(), nullable=True),
        sa.Column("product_link", sa.Text(), nullable=True),
        sa.Column("market_link", sa.Text(), nullable=True),
        sa.Column("original_link", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("reply", sa.Text(), nullable=True),
        sa.Column("reply_status", sa.Text(), nullable=False),
        sa.Column("replied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inquiry_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_samba_cs_inquiry_inquiry_type"),
        "samba_cs_inquiry",
        ["inquiry_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_samba_cs_inquiry_market"), "samba_cs_inquiry", ["market"], unique=False
    )
    op.create_index(
        op.f("ix_samba_cs_inquiry_market_order_id"),
        "samba_cs_inquiry",
        ["market_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_samba_cs_inquiry_reply_status"),
        "samba_cs_inquiry",
        ["reply_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_samba_cs_inquiry_reply_status"), table_name="samba_cs_inquiry"
    )
    op.drop_index(
        op.f("ix_samba_cs_inquiry_market_order_id"), table_name="samba_cs_inquiry"
    )
    op.drop_index(op.f("ix_samba_cs_inquiry_market"), table_name="samba_cs_inquiry")
    op.drop_index(
        op.f("ix_samba_cs_inquiry_inquiry_type"), table_name="samba_cs_inquiry"
    )
    op.drop_table("samba_cs_inquiry")
    # ### end Alembic commands ###
