"""add_samba_license_table

Revision ID: c58d77ec580e
Revises: z_lotteon_order_line_keys
Create Date: 2026-04-22 16:37:12.695208

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c58d77ec580e"
down_revision: Union[str, Sequence[str], None] = "z_lotteon_order_line_keys"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "samba_license",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("license_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("buyer_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("buyer_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_samba_license_license_key"),
        "samba_license",
        ["license_key"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_samba_license_license_key"), table_name="samba_license")
    op.drop_table("samba_license")
    # ### end Alembic commands ###
