"""samba_jobs 테이블 생성

Revision ID: d53a0e1e5c2c
Revises: 89c6e7df240e
Create Date: 2026-03-24 23:44:26.160608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd53a0e1e5c2c'
down_revision: Union[str, Sequence[str], None] = '89c6e7df240e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samba_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('job_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('current', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samba_jobs_job_type'), 'samba_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_samba_jobs_status'), 'samba_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_samba_jobs_tenant_id'), 'samba_jobs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_samba_jobs_tenant_id'), table_name='samba_jobs')
    op.drop_index(op.f('ix_samba_jobs_status'), table_name='samba_jobs')
    op.drop_index(op.f('ix_samba_jobs_job_type'), table_name='samba_jobs')
    op.drop_table('samba_jobs')
    # ### end Alembic commands ###
