"""add_samba_user_table

Revision ID: d589705d6476
Revises: 64fc7a5e6754
Create Date: 2026-03-20 08:33:33.254653

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "d589705d6476"
down_revision: Union[str, Sequence[str], None] = "64fc7a5e6754"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "samba_user",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_samba_user_email"), "samba_user", ["email"], unique=True)
    op.create_index(
        op.f("ix_samba_user_status"), "samba_user", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_samba_user_status"), table_name="samba_user")
    op.drop_index(op.f("ix_samba_user_email"), table_name="samba_user")
    op.drop_table("samba_user")
    # ### end Alembic commands ###
