"""멀티테넌트 유니크 제약 수정: 수집상품 테넌트스코프 + 주문번호 복합유니크

Revision ID: d9c4ff7d6d2e
Revises: 91c5a0e05167
Create Date: 2026-04-16 11:08:08.008997

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d9c4ff7d6d2e"
down_revision: Union[str, Sequence[str], None] = "91c5a0e05167"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("samba_tenants")
    op.drop_index(
        op.f("ix_samba_sns_auto_config_tenant_id"), table_name="samba_sns_auto_config"
    )
    op.drop_table("samba_sns_auto_config")
    op.drop_index(
        op.f("ix_samba_sns_keyword_group_tenant_id"),
        table_name="samba_sns_keyword_group",
    )
    op.drop_table("samba_sns_keyword_group")
    op.drop_index(op.f("ix_samba_cs_inquiry_account_id"), table_name="samba_cs_inquiry")
    op.drop_index(
        op.f("ix_samba_cs_inquiry_collected_product_id"), table_name="samba_cs_inquiry"
    )
    op.drop_index(
        op.f("ix_samba_cs_inquiry_external_id"), table_name="samba_cs_inquiry"
    )
    op.drop_index(
        op.f("ix_samba_cs_inquiry_inquiry_type"), table_name="samba_cs_inquiry"
    )
    op.drop_index(op.f("ix_samba_cs_inquiry_market"), table_name="samba_cs_inquiry")
    op.drop_index(
        op.f("ix_samba_cs_inquiry_market_inquiry_no"), table_name="samba_cs_inquiry"
    )
    op.drop_index(
        op.f("ix_samba_cs_inquiry_market_order_id"), table_name="samba_cs_inquiry"
    )
    op.drop_index(
        op.f("ix_samba_cs_inquiry_market_product_no"), table_name="samba_cs_inquiry"
    )
    op.drop_index(
        op.f("ix_samba_cs_inquiry_reply_status"), table_name="samba_cs_inquiry"
    )
    op.drop_table("samba_cs_inquiry")
    op.drop_index(op.f("ix_samba_wp_site_tenant_id"), table_name="samba_wp_site")
    op.drop_table("samba_wp_site")
    op.drop_index(op.f("ix_samba_sns_post_tenant_id"), table_name="samba_sns_post")
    op.drop_table("samba_sns_post")
    op.drop_index(
        op.f("ix_scp_brand_trgm"),
        table_name="samba_collected_product",
        postgresql_ops={"brand": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(op.f("ix_scp_created_at_desc"), table_name="samba_collected_product")
    op.drop_index(
        op.f("ix_scp_name_trgm"),
        table_name="samba_collected_product",
        postgresql_ops={"name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_scp_source_site_created_at"), table_name="samba_collected_product"
    )
    op.drop_index(op.f("ix_scp_updated_at_desc"), table_name="samba_collected_product")
    op.drop_index(op.f("uq_scp_source_product"), table_name="samba_collected_product")
    op.create_index(
        "uq_scp_tenant_source_product",
        "samba_collected_product",
        ["tenant_id", "source_site", "site_product_id"],
        unique=True,
        postgresql_where=sa.text("site_product_id IS NOT NULL"),
    )
    op.alter_column(
        "samba_detail_template",
        "id",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(length=30),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_samba_login_history_created_at"), table_name="samba_login_history"
    )
    op.alter_column(
        "samba_name_rule",
        "id",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(length=30),
        existing_nullable=False,
    )
    op.create_index(
        "uq_order_tenant_number",
        "samba_order",
        ["tenant_id", "order_number"],
        unique=True,
    )
    op.alter_column(
        "samba_return",
        "tenant_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "samba_sourcing_account",
        "id",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(length=30),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "samba_sourcing_account",
        "id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=30),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "samba_return",
        "tenant_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_index("uq_order_tenant_number", table_name="samba_order")
    op.alter_column(
        "samba_name_rule",
        "id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=30),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_samba_login_history_created_at"),
        "samba_login_history",
        ["created_at"],
        unique=False,
    )
    op.alter_column(
        "samba_detail_template",
        "id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=30),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_index(
        "uq_scp_tenant_source_product",
        table_name="samba_collected_product",
        postgresql_where=sa.text("site_product_id IS NOT NULL"),
    )
    op.create_index(
        op.f("uq_scp_source_product"),
        "samba_collected_product",
        ["source_site", "site_product_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_scp_updated_at_desc"),
        "samba_collected_product",
        [sa.literal_column("updated_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_scp_source_site_created_at"),
        "samba_collected_product",
        ["source_site", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_scp_name_trgm"),
        "samba_collected_product",
        ["name"],
        unique=False,
        postgresql_ops={"name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_scp_created_at_desc"),
        "samba_collected_product",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_scp_brand_trgm"),
        "samba_collected_product",
        ["brand"],
        unique=False,
        postgresql_ops={"brand": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_table(
        "samba_sns_post",
        sa.Column("id", sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        sa.Column("tenant_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "wp_site_id", sa.VARCHAR(length=30), autoincrement=False, nullable=True
        ),
        sa.Column("wp_post_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "category", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "keyword", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column("source_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "status",
            sa.VARCHAR(length=20),
            server_default=sa.text("'draft'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "language",
            sa.VARCHAR(length=5),
            server_default=sa.text("'ko'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "product_ids",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "published_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("samba_sns_post_pkey")),
    )
    op.create_index(
        op.f("ix_samba_sns_post_tenant_id"),
        "samba_sns_post",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "samba_wp_site",
        sa.Column("id", sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        sa.Column("tenant_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("site_url", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "username", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("app_password", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "site_name", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "status",
            sa.VARCHAR(length=20),
            server_default=sa.text("'active'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("samba_wp_site_pkey")),
    )
    op.create_index(
        op.f("ix_samba_wp_site_tenant_id"), "samba_wp_site", ["tenant_id"], unique=False
    )
    op.create_table(
        "samba_cs_inquiry",
        sa.Column("id", sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        sa.Column("market", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("market_order_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("account_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("inquiry_type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("questioner", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("product_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("product_link", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("market_link", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("original_link", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("reply", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("reply_status", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "replied_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "inquiry_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "collected_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("product_image", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("market_inquiry_no", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("market_answer_no", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "collected_product_id", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column("market_product_no", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "is_hidden",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("account_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("external_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "external_sent",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("samba_cs_inquiry_pkey")),
    )
    op.create_index(
        op.f("ix_samba_cs_inquiry_reply_status"),
        "samba_cs_inquiry",
        ["reply_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_samba_cs_inquiry_market_product_no"),
        "samba_cs_inquiry",
        ["market_product_no"],
        unique=False,
    )
    op.create_index(
        op.f("ix_samba_cs_inquiry_market_order_id"),
        "samba_cs_inquiry",
        ["market_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_samba_cs_inquiry_market_inquiry_no"),
        "samba_cs_inquiry",
        ["market_inquiry_no"],
        unique=False,
    )
    op.create_index(
        op.f("ix_samba_cs_inquiry_market"), "samba_cs_inquiry", ["market"], unique=False
    )
    op.create_index(
        op.f("ix_samba_cs_inquiry_inquiry_type"),
        "samba_cs_inquiry",
        ["inquiry_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_samba_cs_inquiry_external_id"),
        "samba_cs_inquiry",
        ["external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_samba_cs_inquiry_collected_product_id"),
        "samba_cs_inquiry",
        ["collected_product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_samba_cs_inquiry_account_id"),
        "samba_cs_inquiry",
        ["account_id"],
        unique=False,
    )
    op.create_table(
        "samba_sns_keyword_group",
        sa.Column("id", sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        sa.Column("tenant_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "category", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "keywords",
            postgresql.JSON(astext_type=sa.Text()),
            server_default=sa.text("'[]'::json"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("samba_sns_keyword_group_pkey")),
    )
    op.create_index(
        op.f("ix_samba_sns_keyword_group_tenant_id"),
        "samba_sns_keyword_group",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "samba_sns_auto_config",
        sa.Column("id", sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        sa.Column("tenant_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "wp_site_id", sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
        sa.Column(
            "interval_minutes",
            sa.INTEGER(),
            server_default=sa.text("20"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "max_daily_posts",
            sa.INTEGER(),
            server_default=sa.text("150"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_running",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "language",
            sa.VARCHAR(length=5),
            server_default=sa.text("'ko'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "include_product_banner",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("product_banner_html", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "today_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_posted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("samba_sns_auto_config_pkey")),
    )
    op.create_index(
        op.f("ix_samba_sns_auto_config_tenant_id"),
        "samba_sns_auto_config",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "samba_tenants",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "owner_user_id",
            sa.VARCHAR(),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "plan",
            sa.VARCHAR(),
            server_default=sa.text("'free'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "limits",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "subscription_start",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "subscription_end",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "autotune_enabled",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("samba_tenants_pkey")),
    )
    # ### end Alembic commands ###
